name: Auto Release GoFSUtil

on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  csm-release:
    uses: meggm/common-github-actions-test/.github/workflows/versioning.yaml@main
    name: Versioning Workflow
    secrets: inherit

  trigger-versioning-workflow:
    name: Trigger Versioning Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch Event to Versioning Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ github.repository }} # Current repository
          event-type: trigger-versioning-workflow
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
