name: Auto Release CSM
on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
        description: "The version to be used. If not provided, it will be calculated."
      image:
        required: true
        type: string
        description: "The image to be used in the common workflow."
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  calculate-version:
    if: ${{ inputs.version == null }}
    runs-on: ubuntu-latest
    outputs:
      new-version: ${{ steps.set-version.outputs.version }}
    steps:
      # Step 1: Check out the repository with full history and tags
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch the full history including tags

      # Step 2: Fetch the latest release version
      - name: Get latest release version
        id: get-latest-version
        run: |
          latest_version=$(git describe --tags $(git rev-list --tags --max-count=1))
          echo "latest_version=${latest_version}" >> $GITHUB_ENV

      # Step 3: Increment minor version and remove 'v' prefix
      - name: Increment minor version and remove 'v' prefix
        id: set-version
        run: |
          # Use the fetched latest_version from environment
          version=${{ env.latest_version }}
          clean_version=${version#v} 
          
          # Parse version parts
          major=$(echo $clean_version | cut -d'.' -f1)
          minor=$(echo $clean_version | cut -d'.' -f2)
          patch=$(echo $clean_version | cut -d'.' -f3)
          new_minor=$((minor + 1)) 
          new_version="${major}.${new_minor}.0"
          
          echo "New version: $new_version"
          echo "::set-output name=version::$new_version"

  csm-release:
    needs: calculate-version
    uses: meggm/common-github-actions-test/.github/workflows/versioning.yaml@main
    with:
      version: ${{ inputs.version || needs.calculate-version.outputs.new-version }}
      image: ${{ inputs.image }}
    secrets: inherit
