name: Auto Release GoFSUtil
on:
  workflow_call:
  workflow_dispatch:
  repository_dispatch:
    types: [auto-driver-module-release-workflow]

jobs:
  csm-release:
    uses: meggm/common-github-actions-test/.github/workflows/versioning.yaml@main
    name: Versioning Workflow
    secrets: inherit
