name: Manual Release

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true
      image:
        description: 'Version to release (major, minor, patch) Ex: 1.0.0'
        required: true

jobs:
  release:
    uses: meggm/common-github-actions-test/.github/workflows/csm-release-driver-module.yaml@main
    name: Release CSM Drivers and Modules
    with:
      version: ${{ github.event.inputs.version }}
      image: ${{ github.event.inputs.image }}
    secrets: inherit
